<?php
/**
 * PostFinance Checkout Magento 2
 *
 * This Magento 2 extension enables to process payments with PostFinance Checkout (https://postfinance.ch/en/business/products/e-commerce/postfinance-checkout-all-in-one.html).
 *
 * @package PostFinanceCheckout_Payment
 * @author PostFinance Ltd (https://postfinance.ch/en/business/products/e-commerce/postfinance-checkout-all-in-one.html)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)

 */
/** @var Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var PostFinanceCheckout\Payment\ViewModel\WhitelabelMachineNameCheckoutViewModel $viewModel */

$viewModel = $block->getViewModel();
$method = $block->getMethod();
if (!$method) {
    return;
}
$methodCode = $method->getCode();

// Only proceed if it's one of our payment methods.
if (strpos($methodCode, 'postfinancecheckout_payment_') !== 0) {
    return;
}

$configData = $viewModel->getPaymentIntegrationData($methodCode);
$configData['methodCode'] = $methodCode;
?>

<div x-data="hyvaCheckoutWhitelabelPaymentMethod"
     data-config="<?= $escaper->escapeHtmlAttr(json_encode($configData)) ?>"
     class="postfinancecheckout-payment-method-container mt-4"
     id="postfinancecheckout-container-<?= $escaper->escapeHtmlAttr($methodCode) ?>">
    
    <div
        x-show="isIframeMode"
        id="postfinancecheckout-iframe-<?= $escaper->escapeHtmlAttr($methodCode) ?>"
        class="postfinancecheckout-iframe-wrapper border rounded p-2 bg-white shadow-sm" style="display: none;"
        >
        <!-- Iframe will be mounted here -->
    </div>
</div>
